/**
 * Generates a printable card sheet for beneficiaries
 * @param {Array} beneficiaries - Array of beneficiary objects with name, uniqueId, and qrCodeUrl
 * @param {string} outputPath - Path to save the generated HTML file
 */
function generateCardSheet(beneficiaries, outputPath) {
    // Validate input
    if (!Array.isArray(beneficiaries)) {
        throw new Error('Beneficiaries must be an array');
    }
    
    // Create card HTML for each beneficiary
    const cardsHtml = beneficiaries.map(beneficiary => {
        return `
        <div class="beneficiary-card">
            <div class="card-header">
                <div class="logo-placeholder"></div>
                <div class="organization-name">Meal Pass Program 2025</div>
            </div>
            
            <div class="beneficiary-info">
                <div class="beneficiary-name">${escapeHtml(beneficiary.name)}</div>
                <div class="beneficiary-id">${escapeHtml(beneficiary.uniqueId)}</div>
            </div>
            
            <div class="qr-container">
                <img src="${escapeHtml(beneficiary.qrCodeUrl)}" alt="QR Code" class="qr-code" onerror="this.onerror=null;this.src='data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMTAwIiBoZWlnaHQ9IjEwMCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cmVjdCB3aWR0aD0iMTAwIiBoZWlnaHQ9IjEwMCIgZmlsbD0iI2RkZCIvPjx0ZXh0IHg9IjUwIiB5PSI1NSIgZm9udC1mYW1pbHk9IkFyaWFsIiBmb250LXNpemU9IjgiIHRleHQtYW5jaG9yPSJtaWRkbGUiIGZpbGw9IiM2NjYiPkNSQyBOb3QgRm91bmQ8L3RleHQ+PC9zdmc+';">
            </div>
        </div>
        `;
    }).join('\n');
    
    // Create the full HTML document
    const htmlContent = `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Meal Pass Beneficiary Cards</title>
    <link rel="stylesheet" href="./cardSheet.css">
</head>
<body>
    <div class="print-header">
        <div class="logo-placeholder"></div>
        <h1>Meal Pass Program 2025</h1>
    </div>
    
    <div class="card-grid" id="cardGrid">
        ${cardsHtml}
    </div>
    
    <div class="print-footer">
        <p>Generated by Meal Pass System</p>
    </div>
</body>
</html>`;
    
    // In a browser environment, we can't directly write files
    // So we'll create a download link
    if (typeof window !== 'undefined') {
        // Create a Blob with the HTML content
        const blob = new Blob([htmlContent], { type: 'text/html' });
        
        // Create a download link
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = 'beneficiary-cards.html';
        document.body.appendChild(a);
        a.click();
        
        // Clean up
        setTimeout(() => {
            document.body.removeChild(a);
            URL.revokeObjectURL(url);
        }, 100);
        
        return url;
    }
    
    // For Node.js environment (if needed)
    if (typeof module !== 'undefined' && module.exports) {
        return htmlContent;
    }
    
    return htmlContent;
}

/**
 * Escapes HTML characters to prevent XSS
 * @param {string} text - Text to escape
 * @returns {string} Escaped text
 */
function escapeHtml(text) {
    if (!text) return '';
    const map = {
        '&': '&amp;',
        '<': '&lt;',
        '>': '&gt;',
        '"': '&quot;',
        "'": '&#039;'
    };
    return text.replace(/[&<>"']/g, function(m) { return map[m]; });
}

// Example usage:
// const beneficiaries = [
//     { name: "John Doe", uniqueId: "MP-001", qrCodeUrl: "https://example.com/qr1.png" },
//     { name: "Jane Doe", uniqueId: "MP-002", qrCodeUrl: "https://example.com/qr2.png" }
// ];
// generateCardSheet(beneficiaries);

// For Node.js usage:
if (typeof module !== 'undefined' && module.exports) {
    module.exports = { generateCardSheet };
}